# Generated by Django 4.1.7 on 2023-02-25 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_exam_general_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Exam_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('Exam_title', models.CharField(max_length=50, null=True)),
                ('background_image', models.FileField(null=True, upload_to='exam_background')),
                ('start_message', models.TextField()),
                ('end_message', models.TextField()),
                ('layout', models.CharField(choices=[('0', 'One page with all the questions'), ('1', 'One page per section'), ('2', 'One page per question')], max_length=25, null=True)),
                ('progression_mode', models.CharField(choices=[('Percentage', 'Percentage'), ('Number', 'Number')], max_length=25, null=True)),
                ('Exam_time_limit', models.TimeField(null=True)),
                ('selection_mode', models.CharField(choices=[('All questions', 'All questions'), ('Randomized per section', 'Randomized per section')], max_length=25, null=True)),
                ('scoring_mode', models.CharField(choices=[('0', 'No scoring'), ('1', 'Scoring with answers at the end'), ('2', 'Scoring without answers at the end')], max_length=25, null=True)),
                ('access_mode', models.CharField(choices=[('0', 'Anyone with the link'), ('1', 'Invited people only')], max_length=25, null=True)),
                ('Login_required', models.BooleanField(null=True)),
                ('attempt_limit', models.TimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Main_Exam_Master_auth_id', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Main_Exam_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('Exam_title', models.CharField(max_length=50, null=True)),
                ('section_type', models.CharField(choices=[('Section', 'Section'), ('Question', 'Question')], max_length=20, null=True)),
                ('Exam_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Main_Exam_section_exam_id', to='app.main_exam_master')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Main_Question_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('Question', models.CharField(max_length=50, null=True)),
                ('Imagefield', models.FileField(null=True, upload_to='Question_Bank_image')),
                ('Question_type', models.CharField(choices=[('Radio', 'Multiple choice: only one answer'), ('Checkbox', 'Multiple choice: multiple answers allowed')], max_length=20, null=True)),
                ('Description', models.TextField(null=True)),
                ('manadatory', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=25, null=True)),
                ('total_mark', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section_Question_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('Question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Question_Bank_id', to='app.main_question_bank')),
                ('Section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Section_Question_Mapping_id', to='app.main_exam_section')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question_Bank_multiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('question_name', models.CharField(max_length=50, null=True)),
                ('Imagefield', models.FileField(null=True, upload_to='Question_Bank_multiple')),
                ('Mark', models.IntegerField(null=True)),
                ('result_status', models.BooleanField(default=False)),
                ('Question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exam_section_exam_id', to='app.main_question_bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='main_question_bank',
            name='answer_id',
            field=models.ManyToManyField(blank=True, related_name='Answer_master_id', to='app.question_bank_multiple'),
        ),
        migrations.AddField(
            model_name='main_question_bank',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='main_question_bank',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='main_exam_section',
            name='Question_bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Main_Exam_Master_question_id', to='app.main_question_bank'),
        ),
        migrations.AddField(
            model_name='main_exam_section',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='main_exam_section',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL),
        ),
    ]
