# Generated by Django 4.1.2 on 2023-03-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_question_bank_multiple_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_exam_master',
            name='attempt_limit',
            field=models.IntegerField(null=True),
        ),
    ]
