# Generated by Django 4.1.2 on 2023-03-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_main_exam_master_attempt_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_exam_section',
            old_name='Exam_title',
            new_name='Section_title',
        ),
    ]
