# Generated by Django 4.1.7 on 2023-03-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_attend_status_exam_attend_user_score_result_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_attend_user_score',
            name='user_select_choice',
            field=models.ManyToManyField(related_name='exam_attend_user_score_Question_Bank_id_select_id', to='app.question_bank_multiple_choice'),
        ),
    ]
