# Generated by Django 4.1.7 on 2023-02-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_details_class_id', to='app.class_master'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='roll_no',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
