# Generated by Django 4.1.7 on 2023-02-23 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_student_details_class_id_student_details_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('question', models.TextField()),
                ('option_A', models.CharField(max_length=25, null=True)),
                ('option_B', models.CharField(max_length=25, null=True)),
                ('option_C', models.CharField(max_length=25, null=True)),
                ('option_D', models.CharField(max_length=25, null=True)),
                ('answer', models.CharField(max_length=25, null=True)),
                ('mark', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Question_bank_subject_id', to='app.subject_master')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
