# Generated by Django 4.1.7 on 2023-02-25 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_main_exam_master_main_exam_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Bank_multiple_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('choice', models.CharField(max_length=50, null=True)),
                ('Imagefield', models.FileField(null=True, upload_to='Question_Bank_multiple')),
                ('Mark', models.IntegerField(null=True)),
                ('result_status', models.BooleanField(default=False)),
                ('Question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exam_section_exam_id', to='app.main_question_bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Question_Bank_multiple',
        ),
        migrations.AlterField(
            model_name='main_question_bank',
            name='answer_id',
            field=models.ManyToManyField(blank=True, related_name='Answer_master_id', to='app.question_bank_multiple_choice'),
        ),
    ]
