# Generated by Django 4.1.2 on 2023-03-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_exam_title_main_exam_section_section_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_exam_section',
            old_name='Section_title',
            new_name='section_title',
        ),
    ]
