# Generated by Django 4.1.7 on 2023-03-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_exam_inital_field_choice_exam_inital_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_inital_field_choice',
            name='initial_field_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exam_inital_field_id', to='app.exam_inital_field'),
        ),
    ]
