# Generated by Django 4.1.7 on 2023-03-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_question_bank_multiple_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_exam_section',
            old_name='Exam_title',
            new_name='section_title',
        ),
        migrations.AlterField(
            model_name='main_exam_master',
            name='attempt_limit',
            field=models.IntegerField(null=True),
        ),
    ]
