# Generated by Django 4.1.7 on 2023-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_exam_inital_field_choice_initial_field_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
            ],
        ),
    ]
